version: '2'

services:
  db: 
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db:
    external: false